# Deploy database
---
version: '3.1'

services:
  database:
    image: shaleka/tech230-database:v1
    restart: always
    ports:
      - 27017:27017

# Deploy app

  sparta-app:
    image: shaleka/tech230-sparta-app:v1
    restart: always
    
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DB_HOST=database:27017/posts
    command: >
      sh -c "npm install && npm start"

