apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo-app
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo
          image: bradleywoods/mongo-database:v2
          ports:
            - containerPort: 27017


