apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: default
spec:
  ports:
    #- nodePort: 30003
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-app
  type: NodePort
