apiVersion: apps/v1

kind: Deployment #pod - service what kind of service/object

#what would you like to call it - name the service

metadata:

  name: nginx-deployment # naming the deployment

spec:

  selector:

    matchLabels:

      app: nginx # look for this label to match with k8 service

    # lets create a replica set of this with instances/pods

  replicas: 3 # 3 pods

    # template to use it's label for K8 service to launch in

  template:

    metadata:

      labels:

        app: nginx




    spec:

      containers:

      - name: nginx

        image: shaleka/tech230_docker:v1

        ports:

        - containerPort: 80
